# Generated by Django 4.1 on 2022-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0007_alter_userprofile_image_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_friend',
            field=models.ManyToManyField(blank=True, default='', related_name='user_friend', to='chatApp.friend'),
        ),
    ]
