# Generated by Django 4.1 on 2022-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0008_alter_userprofile_user_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/defaultimg.jpg', null=True, upload_to=''),
        ),
    ]
