# Generated by Django 4.1 on 2022-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0009_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/defaultimg.jpg', null=True, upload_to=''),
        ),
    ]
