# Generated by Django 4.1.1 on 2022-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0011_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, default='', related_name='users_friends', to='chatApp.userprofile'),
        ),
    ]
